---
version: "3"
services:
  php:
<<<<<<< HEAD
    # image: "becodeorg/php"
    build: "./"
=======
    build: './'
>>>>>>> 481f66a1d071ca4eda6ec3f1d8ae5a39c06498ad
    volumes:
      - "./src:/var/www/html"
    ports:
      - "80:80"
  mysql:
    image: "mariadb"
    restart: "unless-stopped"
    volumes:
      - "mysql_db:/var/lib/mysql"
    ports:
      - "3307:3307"
      - "33070:33070"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8001:80"
    depends_on:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
volumes:
  mysql_db:
